name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.0'  # Specify the Go version

      - name: Build
        run: go build ./...  # Run the build com

      # Upload build output
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: pb
          retention-days: 1